<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <OutputPath>bin\</OutputPath>
    <AssemblyName>PopupLayoutTests</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Compile Include="PopupLayoutTests.cs" />
    <Compile Include="..\..\ResponsiveTableLayoutPanel.cs" />
    <Compile Include="..\..\MailInputForm.cs" />
    <Compile Include="..\..\ProgressForm.cs" />
    <Compile Include="..\..\ProgressForm.Designer.cs" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
